name: WebManager-Test
main: kr.apo2073.Main
version: ${version}
api-version: 1.21
author: [ apo2073 ]
depend: [PlaceholderAPI]
commands:
  auth:
    description: WebManager Auth Command
    permission: apo.wm.auth